/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import controller.ControladorCursos;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.*;
import main.Main;
/**
 *
 * @author Joan
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName());
    public static final DefaultListModel<String> modelo = new DefaultListModel<>();
    public static VentanaCurso vCurso;
    public static String seleccionado;
    /**
     * Creates new form a
     */
    public VentanaPrincipal() {
        initComponents();
        //Carga cursos
        modelo.clear();
        for(String curso: Main.CARPETA_DATOS.list()){
            modelo.addElement(curso);
        }
        actualizar();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        numAlumnos = new javax.swing.JLabel();
        sahur = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        eliminar = new javax.swing.JButton();
        abrir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaCursos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        numAlumnos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        numAlumnos.setText("Numero de alumnos: 0");

        sahur.setBackground(new java.awt.Color(255, 153, 153));
        sahur.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sahur.setForeground(new java.awt.Color(51, 51, 51));
        sahur.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/si.png"))); // NOI18N
        sahur.addActionListener(this::sahurActionPerformed);

        crear.setText("Crear Curso");
        crear.addActionListener(this::crearActionPerformed);

        eliminar.setText("Eliminar Curso");
        eliminar.addActionListener(this::eliminarActionPerformed);

        abrir.setText("Abrir Curso");
        abrir.addActionListener(this::abrirActionPerformed);

        listaCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaCursos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(numAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sahur, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(sahur, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(numAlumnos)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crear, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(abrir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed
        ControladorCursos.crear();
        //Recarga la lista
        actualizar();
        
    }//GEN-LAST:event_crearActionPerformed

    private void eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarActionPerformed
        seleccionado = listaCursos.getSelectedValue();
        ControladorCursos.eliminar(seleccionado);
        //Recarga la lista
        actualizar();
    }//GEN-LAST:event_eliminarActionPerformed

    private void abrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirActionPerformed
        seleccionado = listaCursos.getSelectedValue();
        vCurso = new VentanaCurso();
        vCurso.setVisible(true);        
        
        dispose();
    }//GEN-LAST:event_abrirActionPerformed

    private void sahurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sahurActionPerformed
        ImageIcon imagen = new ImageIcon(getClass().getResource("Akashdeep Singh Kaur.png"));
        JOptionPane pane = new JOptionPane(
                "Hola soy Akashdeep\nAquí tienes los valores seleccionados:\n     · Valor:"
                + listaCursos.getSelectedValue() + "\n     · Indice: " + (int)(listaCursos.getSelectedIndex()+1),
                JOptionPane.INFORMATION_MESSAGE,
                JOptionPane.DEFAULT_OPTION,
                imagen
        );
        JDialog dialog = pane.createDialog("Imagen");
        dialog.setVisible(true);
        
    }//GEN-LAST:event_sahurActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VentanaPrincipal().setVisible(true));
    }
    
    public final void actualizar(){
        listaCursos.setModel(modelo);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir;
    private javax.swing.JButton crear;
    private javax.swing.JButton eliminar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> listaCursos;
    private javax.swing.JLabel numAlumnos;
    private javax.swing.JButton sahur;
    // End of variables declaration//GEN-END:variables
}
